services:
  - type: web
    name: vehicle-parking-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app
    envVars:
      - key: FLASK_ENV
        value: production
      - key: SECRET_KEY
        value: 12345
